---
- hosts: all
  tasks:

    - shell: mkdir -p ~/tmp/bb-worker 

    - name: Go to the folder and execute command to setup worker
      command: bash -lc "cd ~/tmp/bb-worker && virtualenv --no-site-packages sandbox && source sandbox/bin/activate && pip install --upgrade pip && pip install buildbot-worker && pip install setuptools-trial && buildbot-worker create-worker worker localhost example-worker pass && buildbot-worker start worker "
